name: CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm ci
      - run: npm run test
      - run: echo SUCCESS
